cards:
  - entities:
      - sensor.rbr50_gateway_kbyte_sec_sent
      - sensor.rbr50_gateway_bytes_received
      - sensor.rbr50_gateway_packets_sec_sent
      - sensor.rbr50_gateway_packets_sec_received
      - sensor.rbr50_gateway_bytes_sent
      - sensor.rbr50_gateway_packets_sent
      - sensor.rbr50_gateway_kbyte_sec_received
      - sensor.rbr50_gateway_packets_received
    show_header_toggle: false
    title: Network Details
    type: entities
icon: 'fas:cogs'
path: settings
title: "Settings"
