- id: '1560117810824'
  alias: Start Homekit
  trigger:
  - event_data: {}
    event_type: zwave.network_ready
    platform: event
  - event_data: {}
    event_type: zwave.network_complete
    platform: event
  - event_data: {}
    event_type: zwave.network_complete_some_dead
    platform: event
  condition: []
  action:
  - service: homekit.start

- alias: Mark person as just arrived
  trigger:
    - platform: state
      entity_id: device_tracker.mike
      from: 'not_home'
      to: 'home'
    - platform: state
      entity_id: group.debbie
      from: 'not_home'
      to: 'home'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'device_tracker.mike' %}
            input_select.mike_status_dropdown
          {% else %}
            input_select.debbie_status_dropdown
          {% endif %}
        option: Just Arrived

- alias: Mark person as home
  trigger:
    - platform: state
      entity_id: input_select.mike_status_dropdown
      to: 'Just Arrived'
      for:
        minutes: 10
    - platform: state
      entity_id: input_select.debbie_status_dropdown
      to: 'Just Arrived'
      for:
        minutes: 10
    - platform: state
      entity_id: input_select.mike_status_dropdown
      from: 'Just Left'
      to: 'Just Arrived'
    - platform: state
      entity_id: input_select.debbie_status_dropdown
      from: 'Just Left'
      to: 'Just Arrived'
  condition:
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'input_select.mike_status_dropdown' %}
            input_select.mike_status_dropdown
          {% else %}
            input_select.debbie_status_dropdown
          {% endif %}
        option: Home

- alias: Mark person as just left
  trigger:
    - platform: state
      entity_id: device_tracker.mike
      from: 'home'
      to: 'not_home'
    - platform: state
      entity_id: group.debbie
      from: 'home'
      to: 'not_home'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'device_tracker.mike' %}
            input_select.mike_status_dropdown
          {% else %}
            input_select.debbie_status_dropdown
          {% endif %}
        option: Just Left

- alias: Mark person as away
  trigger:
    - platform: state
      entity_id: input_select.mike_status_dropdown
      to: 'Just Left'
      for:
        minutes: 10
    - platform: state
      entity_id: input_select.debbie_status_dropdown
      to: 'Just Left'
      for:
        minutes: 10
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'input_select.mike_status_dropdown' %}
            input_select.mike_status_dropdown
          {% else %}
            input_select.debbie_status_dropdown
          {% endif %}
        option: Away

- alias: Mark person as extended away
  trigger:
    - platform: state
      entity_id: input_select.mike_status_dropdown
      to: 'Away'
      for:
        hours: 24
    - platform: state
      entity_id: input_select.debbie_status_dropdown
      to: 'Away'
      for:
        hours: 24
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'input_select.mike_status_dropdown' %}
            input_select.mike_status_dropdown
          {% else %}
            input_select.debbie_status_dropdown
          {% endif %}
        option: Extended Away
  
- alias: 'System - Set Custom Theme at Startup'
  initial_state: 'true'
  trigger:
    platform: homeassistant
    event: start
  action:
    service: frontend.set_theme
    data:
      name: slate